//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mintrans.Mstk.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mintrans.Mstk.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение показателей.
        /// </summary>
        public static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр данных по показателю.
        /// </summary>
        public static string ChartTitleSingle {
            get {
                return ResourceManager.GetString("ChartTitleSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список добавленных к сравнению элементов будет сброшен. Продолжить?.
        /// </summary>
        public static string ConfirmQuestion {
            get {
                return ResourceManager.GetString("ConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горизонтальный.
        /// </summary>
        public static string Monitor_Chart_Options_HorizontalType {
            get {
                return ResourceManager.GetString("Monitor_Chart_Options_HorizontalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линейный.
        /// </summary>
        public static string Monitor_Chart_Options_LineType {
            get {
                return ResourceManager.GetString("Monitor_Chart_Options_LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string Monitor_Chart_Options_MapType {
            get {
                return ResourceManager.GetString("Monitor_Chart_Options_MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        public static string Monitor_Chart_Options_TableType {
            get {
                return ResourceManager.GetString("Monitor_Chart_Options_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вертикальный.
        /// </summary>
        public static string Monitor_Chart_Options_VerticalType {
            get {
                return ResourceManager.GetString("Monitor_Chart_Options_VerticalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мониторинг состояния транспортного комплекса.
        /// </summary>
        public static string MSTK_DataMartCaption {
            get {
                return ResourceManager.GetString("MSTK_DataMartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Департамент транспорта г. Москвы.
        /// </summary>
        public static string mstk_dtMos {
            get {
                return ResourceManager.GetString("mstk_dtMos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Федеральное дорожное агентство (Росавтодор) - Российская газета.
        /// </summary>
        public static string mstk_feddoragentstvo {
            get {
                return ResourceManager.GetString("mstk_feddoragentstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Федеральное агентство железнодорожного транспорта (Росжелдор) - Российская газета.
        /// </summary>
        public static string mstk_fedzhdtrans {
            get {
                return ResourceManager.GetString("mstk_fedzhdtrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство транспорта.
        /// </summary>
        public static string mstk_mintrans {
            get {
                return ResourceManager.GetString("mstk_mintrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство транспорта - Российская газета.
        /// </summary>
        public static string mstk_mintranssvyaz {
            get {
                return ResourceManager.GetString("mstk_mintranssvyaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РБК.
        /// </summary>
        public static string mstk_rbc {
            get {
                return ResourceManager.GetString("mstk_rbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспорт РФ.
        /// </summary>
        public static string mstk_rostransport {
            get {
                return ResourceManager.GetString("mstk_rostransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Федеральное агентство воздушного транспорта (Росавиация) - Российская газета.
        /// </summary>
        public static string mstk_transvozdux {
            get {
                return ResourceManager.GetString("mstk_transvozdux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Федеральное агентство морского и речного транспорта (Росморречфлот) - Российская газета.
        /// </summary>
        public static string mstk_vodntransport {
            get {
                return ResourceManager.GetString("mstk_vodntransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.Новости: Транспорт.
        /// </summary>
        public static string mstk_yandex {
            get {
                return ResourceManager.GetString("mstk_yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Коммерсантъ&quot;. Происшествия.
        /// </summary>
        public static string mtb_korrespondent {
            get {
                return ResourceManager.GetString("mtb_korrespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РБК.
        /// </summary>
        public static string mtb_rbc {
            get {
                return ResourceManager.GetString("mtb_rbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Российское Информационное Агентство &quot;РИА Новости&quot;.
        /// </summary>
        public static string mtb_ria {
            get {
                return ResourceManager.GetString("mtb_ria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЕСТИ.
        /// </summary>
        public static string mtb_vesti {
            get {
                return ResourceManager.GetString("mtb_vesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.Новости: Происшествия.
        /// </summary>
        public static string mtb_yandex {
            get {
                return ResourceManager.GetString("mtb_yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка показателей.
        /// </summary>
        public static string Navigation_Edit_Text {
            get {
                return ResourceManager.GetString("Navigation_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Navigation_General_Text {
            get {
                return ResourceManager.GetString("Navigation_General_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реестр имущества.
        /// </summary>
        public static string Navigation_IndicatorEdit_Text {
            get {
                return ResourceManager.GetString("Navigation_IndicatorEdit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индикаторы.
        /// </summary>
        public static string Navigation_IndicatorWatch_Text {
            get {
                return ResourceManager.GetString("Navigation_IndicatorWatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор СМИ.
        /// </summary>
        public static string Navigation_Media_Text {
            get {
                return ResourceManager.GetString("Navigation_Media_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели.
        /// </summary>
        public static string Navigation_Member_Text {
            get {
                return ResourceManager.GetString("Navigation_Member_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения показателей.
        /// </summary>
        public static string Navigation_MemberValues_Text {
            get {
                return ResourceManager.GetString("Navigation_MemberValues_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты ТК.
        /// </summary>
        public static string Navigation_Objects_Text {
            get {
                return ResourceManager.GetString("Navigation_Objects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string NoDataLabel {
            get {
                return ResourceManager.GetString("NoDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите справочник:.
        /// </summary>
        public static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите справочник для построения строк таблицы.
        /// </summary>
        public static string OptionMainLabel {
            get {
                return ResourceManager.GetString("OptionMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пресса.
        /// </summary>
        public static string PressPageTitle {
            get {
                return ResourceManager.GetString("PressPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнены обязательные поля.
        /// </summary>
        public static string ProfValidRes_NoReqData {
            get {
                return ResourceManager.GetString("ProfValidRes_NoReqData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное описание блока.
        /// </summary>
        public static string ProfValRes_TooLongBlockDesc {
            get {
                return ResourceManager.GetString("ProfValRes_TooLongBlockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное наименование блока.
        /// </summary>
        public static string ProfValRes_TooLongBlockName {
            get {
                return ResourceManager.GetString("ProfValRes_TooLongBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное описание.
        /// </summary>
        public static string ProfValRes_TooLongDesc {
            get {
                return ResourceManager.GetString("ProfValRes_TooLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное наименование.
        /// </summary>
        public static string ProfValRes_TooLongName {
            get {
                return ResourceManager.GetString("ProfValRes_TooLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для отображения данных необходимо выбрать показатель или изменить условия фильтра..
        /// </summary>
        public static string SelectMemberLabel {
            get {
                return ResourceManager.GetString("SelectMemberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При выполнении действия произошла неожиданная ошибка. Подробная информация записана в журнал..
        /// </summary>
        public static string UnexpectedErrorInAction {
            get {
                return ResourceManager.GetString("UnexpectedErrorInAction", resourceCulture);
            }
        }
    }
}
